"""aggiunto campo scadenza token verifica email

Revision ID: 22cf6733dcd2
Revises: add9c3e6860c
Create Date: 2025-12-01 16:40:34.129918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22cf6733dcd2'
down_revision: Union[str, Sequence[str], None] = 'add9c3e6860c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verify_email_token_expiration', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verify_email_token_expiration')
    # ### end Alembic commands ###
