"""aggiunto token verifica email

Revision ID: add9c3e6860c
Revises: 1921d7740e84
Create Date: 2025-12-01 11:10:15.389858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add9c3e6860c'
down_revision: Union[str, Sequence[str], None] = '1921d7740e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verify_email_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verify_email_token')
    # ### end Alembic commands ###
